### ISSUE TITLE
implement more complex fare structure

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#451]
- zone-based fare costs
- distance-based fare costs

**Comment by BardyBard** [comment]
- possible to implement pricing for Origin-Destination Zone Model
- don't know for Zone-Transit Model or distance based
- possible for more transfer combos, A-B-C as opposed to just A-B

**Comment by mattwigway** [comment]
I've been thinking about this a bit, and I think there's a way that would be reasonably performant in most cases and would allow implementing arbitrarily complex fare systems without the mess of conditional logic and mind-bending backwards-thinking about what the fare could be in the future that we have in e.g. [the New York City fare calculator](https://github.com/conveyal/r5/blob/dev/docs/fares/newyork.md). The idea would be something akin to the old OTP [path parsers](https://github.com/opentripplanner/OpenTripPlanner/issues/2091)–which proved to be invalid in that application but would be valid in this one. Basically the user would just define a set of fares for full journey based on some kind of matching rule along the lines of a regular expression (but with less cryptic syntax), which could identify rides based on routes, stops, etc., and then define a fare for that entire ride (I've mocked up an example below). Then in the routing, we'd choose the final fare based on the first matched rule for the full ride, and the transfer allowance would just be the set of fares that match this prefix (so in the example below, after a local bus ride, both fares would be part of the transfer allowance, but after a local bus and a subway ride only the second would be). Then we treat prefixes as incomparable if they don't have the same set of potential transfer allowances; we also need to somehow account for where you are in each transfer allowance to account for say that second one after the first local bus ride vs after the subway ride). I think the other challenge is when you have situations where there are not free transfers - do we require the user to exhaustively specify every possible fare or do we allow the the router to come up with combinations (potentially even overlapping, for instance riding a bus from Agency B in between buses from Agency A).

One of the tricky things that required special logic in the Boston fare calculator was that you usually get one pay-the-difference transfer, but you can ride bus -> subway -> bus without paying a new fare for the third bus (see Table 2 of [the original paper on the fare algorithm](https://doi.org/10.17615/ve0k-1m72)). This proposal would neatly solve that without custom logic. A specification of (this part of) the fare system might look something like this (I'm envisioning this would be a YAML/JSON format - yaml for human readable files, json for machine-generated):

```yaml
- name: LocalBus
  fare:
    full: 1.70
    reduced: 0.85
  path:
    - route_type: 3 # bus
      agency_id: mbta
      count: 1-2 # one free transfer

- name: LocalBusSubway
  fare:
    full: 2.40
    reduced: 1.10
  path:
    - route_type: 3 # bus
      agency_id: mbta
      count: 1 # no transfers to second local bus allowed
    - route_type: 1 # subway
      agency_id: mbta
      # free transfer inside paid area
      # a challenge here is that transfers outside the paid area
      # aren't free, so maybe we need like an allowed_transfer_stops
      # or something
      count: 1+
    - route_type: 3 # bus
      agency_id: mbta
      count: 0-1 # optional
```

I haven't followed GTFS-fares v2 development in a while, but I don't think it's been widely adopted and I think it's more complicated than this.
